name: mpflutter_template
description: A new MPFlutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter: "0.10.1"
  flutter_web_plugins: "0.10.1"
  mpcore: "0.10.1"
  mp_build_tools: "0.10.1"
  path_provider: ^2.0.7
  shared_preferences: ^2.0.8
dependency_overrides:
  flutter: "0.10.1"
  mpcore: "0.10.1"
  flutter_web_plugins: "0.10.1"